PhilKes/NotallyX

app/src/main/java/com/omgodse/notally/sorting/ListItemSortedList.kt
app/src/main/java/com/omgodse/notally/sorting/ListItemSortedListExtensions.kt
app/src/test/kotlin/com/omgodse/notally/recyclerview/listmanager/ListManagerMoveTest.kt
app/src/test/kotlin/com/omgodse/notally/recyclerview/listmanager/ListManagerTestBase.kt
app/src/test/kotlin/com/omgodse/notally/sorting/ListItemSortedListTest.kt
app/src/test/kotlin/com/omgodse/notally/test/TestUtils.kt

Fix if first item is child force it to be a parent

---

app/src/main/java/com/omgodse/notally/activities/ConfigureWidget.kt
app/src/main/java/com/omgodse/notally/fragments/NotallyFragment.kt
app/src/main/java/com/omgodse/notally/miscellaneous/Extensions.kt
app/src/main/java/com/omgodse/notally/recyclerview/adapter/BaseNoteAdapter.kt
app/src/main/java/com/omgodse/notally/recyclerview/viewholder/BaseNoteVH.kt
app/src/main/res/layout/recycler_base_note.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values/strings.xml

Closes #15 
Similar to https://github.com/PhilKes/Notally/pull/24, the amount of additional images is now displayed in the main view:

Add display amount of images

---

app/src/main/java/com/philkes/notallyx/presentation/widget/WidgetFactory.kt

Strike through checked item in Widget

---

app/src/main/java/com/philkes/notallyx/NotallyXApplication.kt
app/src/main/java/com/philkes/notallyx/Preferences.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/SettingsFragment.kt
app/src/main/java/com/philkes/notallyx/presentation/view/misc/SeekbarInfo.kt
app/src/main/java/com/philkes/notallyx/utils/backup/AutoBackupWorker.kt
app/src/main/java/com/philkes/notallyx/utils/backup/BackUpUtils.kt
app/src/main/res/layout/fragment_settings.xml
app/src/main/res/values/strings.xml

Closes #31
* Adds 2 new preference values:
* Maximum amount of backups to keep (oldest will be deleted automatically) (default: 3)
* Auto-backup period in days (default: 1)

Add preferences for rolling auto-backups and backup period

---

app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/NotallyFragment.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/viewmodel/BaseNoteModel.kt
app/src/main/java/com/philkes/notallyx/utils/Extensions.kt
app/src/main/res/values/strings.xml

Closes #19
[notallyx_issues_19.webm](https://github.com/user-attachments/assets/11fffadc-b721-4c67-9cef-2fe5531ba3a8)

Show snackbar to undo moving notes

---

app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditListActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditNoteActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/viewmodel/NotallyModel.kt

Closes #86 
* If you exit a Note and its empty (empty `title`, `body`, `items` (for List note) + has no attached `files`, `images`, `audios` or `labels`) it is deleted automatically:
[notallyx_issues_86.webm](https://github.com/user-attachments/assets/d3c81162-5ddd-463f-9e39-9c66baf59db2)

When exiting a note delete it if it's empty

---

app/src/main/java/com/philkes/notallyx/data/model/Folder.kt
app/src/main/java/com/philkes/notallyx/data/model/SearchResult.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/ArchivedFragment.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/DeletedFragment.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/NotesFragment.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/SearchFragment.kt
app/src/main/java/com/philkes/notallyx/presentation/viewmodel/BaseNoteModel.kt
app/src/main/res/navigation/navigation.xml

Closes #68 
* Adds search bar to `Deleted` and `Archived` tabs

Add Search to Deleted and Archived Tabs

---

app/src/main/java/com/philkes/notallyx/data/dao/BaseNoteDao.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/view/misc/tristatecheckbox/TriStateCheckBox.kt
app/src/main/java/com/philkes/notallyx/presentation/view/misc/tristatecheckbox/TriStateCheckboxExtensions.kt
app/src/main/java/com/philkes/notallyx/presentation/viewmodel/BaseNoteModel.kt
app/src/main/res/drawable/check_box_checked.xml
app/src/main/res/drawable/check_box_partial.xml
app/src/main/res/drawable/check_box_unchecked.xml
app/src/main/res/drawable/close.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/choice_item_tri_state.xml

Closes #78 
* Allows to change labels of multiple notes at the same time
Note: If only some of the selected Notes have a certain label, it is displayed as partially-checked ("-" icon)
* Allows to pin/unpin multiple notes at the same time
[notallyx_issues_78.webm](https://github.com/user-attachments/assets/9e9eb8b0-2097-4a83-ba01-f8176cfd2f99)

Allow to pin/label multiple notes

---

app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/NotallyFragment.kt

Closes #91 
* Long clicking a note while in selection mode selects all Notes between the last selected note and the clicked note
[notallyx_issues_91.webm](https://github.com/user-attachments/assets/fb6141ad-1054-4e37-a84e-9892d373c299)

Long click notes to multi-select

---

app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/SearchFragment.kt

Closes #96 
* When opening the search the previous search term is cleared

Clear previous search term

---

app/src/main/res/values-nl/strings.xml

Added missing strings for v6.1

Translate Dutch Language to v6.1

---

app/src/main/java/com/philkes/notallyx/presentation/UiExtensions.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditNoteActivity.kt

Display Link Note after Select All option

---

app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/DisplayLabelFragment.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/NotallyFragment.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditListActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/viewmodel/NotallyModel.kt

Allow adding new note in Label View

---

app/src/main/java/com/philkes/notallyx/presentation/UiExtensions.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt

Closes #140 
[notallyx_issues_140.webm](https://github.com/user-attachments/assets/d2c9bd3c-f735-4c16-9dd3-d0153a044280)

Add change color action to EditNoteActivity

---

app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml

Update chinese translations

---

app/src/main/java/com/philkes/notallyx/data/DataUtil.kt
app/src/main/java/com/philkes/notallyx/presentation/UiExtensions.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/SettingsFragment.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditListActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditNoteActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/view/misc/EditTextAutoClearFocus.kt
app/src/main/java/com/philkes/notallyx/presentation/view/misc/EditTextWithHistory.kt
app/src/main/java/com/philkes/notallyx/presentation/view/misc/HighlightableEditText.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListItemAdapter.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListItemVH.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListManager.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/sorting/ListItemSortedListExtensions.kt
app/src/main/java/com/philkes/notallyx/presentation/viewmodel/preference/Preference.kt
app/src/main/java/com/philkes/notallyx/utils/Extensions.kt
app/src/main/java/com/philkes/notallyx/utils/changehistory/ListPositionValueChange.kt
app/src/main/java/com/philkes/notallyx/utils/changehistory/ValueChange.kt
app/src/main/res/layout/activity_edit.xml
app/src/main/res/values-pl/strings.xml
app/src/main/res/values/strings.xml
app/src/test/kotlin/com/philkes/notallyx/recyclerview/listmanager/ListManagerTestBase.kt

Closes #108 
* Adds search action inside of text or list note:
[notallyx_issues_108_search.webm](https://github.com/user-attachments/assets/7b193f66-cfad-4bbd-a20a-8ee005333215)
[notallyx_issues_108_search_list.webm](https://github.com/user-attachments/assets/87518ced-4eab-43bb-bb59-55ba99e2bd57)

Add Search action in EditNoteActivity

---

app/src/main/res/layout/activity_edit.xml
app/src/main/res/values-it/strings.xml

Fixes bottom appbar cutoff described in #176

Fix BottomAppBar overlap in EditActivity

---

app/src/main/res/values-fr/strings.xml

Well, I guess I translated all missing strings (some of them are not use by the app so I didn't add them)

Full french translation

---

app/build.gradle
app/src/main/java/com/philkes/notallyx/presentation/UiExtensions.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/NotallyFragment.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/settings/SettingsFragment.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
app/src/main/res/drawable/scroll_track.xml
app/src/main/res/layout/activity_edit.xml
app/src/main/res/layout/fragment_notes.xml

Closes #202 
Adds [AndroidFastScroll](https://github.com/zhanghai/AndroidFastScroll) to Notes overview and `EditActivity` (List + Text Notes):
https://github.com/user-attachments/assets/96c6180a-7e59-404c-9446-2924df34211d

Add fast scrollbar to overview and EditActivity

---

app/src/main/java/com/philkes/notallyx/presentation/view/misc/tristatecheckbox/TriStateCheckboxExtensions.kt

Fixes #221 
[notallyx_issues_221.webm](https://github.com/user-attachments/assets/195ec899-2596-454b-8f54-6d8e242f62cf)

Fix CheckBox clickable in Labels dialog

---

app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/NotallyFragment.kt
app/src/main/res/drawable/scroll_thumb.xml
app/src/main/res/drawable/scroll_thumb_shape.xml
app/src/main/res/layout/fragment_notes.xml

Fixes #230 
[notallyx_issues_230_1.webm](https://github.com/user-attachments/assets/653f4f71-c4a9-453f-bfd0-49cbfa517fab)

Use builtin fastscroll of RecyclerView for notes overview

---

app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/settings/SettingsFragment.kt
app/src/main/java/com/philkes/notallyx/presentation/viewmodel/BaseNoteModel.kt
app/src/main/java/com/philkes/notallyx/presentation/viewmodel/preference/NotallyXPreferences.kt
app/src/main/java/com/philkes/notallyx/presentation/viewmodel/preference/Preference.kt

Fixes #231 
If `dataOnExternalStorage` is changed by `Import Settings` or `Reset Settings` the database is moved accordingly

Trigger moving database if dataOnExternalStorage changed by import

---

app/src/main/java/com/philkes/notallyx/data/NotallyDatabase.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/settings/PreferenceBindingExtensions.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt

Fixes #255 
Fixes #256 
- When you press enabled if biometric was already enabled, or disabled if it was already disabled nothing happens
- If biometric lock is enabled but the database is not encrypted, biometric lock is disabled automatically to recover usable state
- If biometric lock is disabled but the database is encrypted, biometric lock is enabled automatically to recover usable state

Fix undo/redo initialization + recover if biometric lock and databas encryption mismatch

---

app/src/main/java/com/philkes/notallyx/presentation/viewmodel/preference/NotallyXPreferences.kt

Reload settings after import

---

app/src/main/java/com/philkes/notallyx/data/NotallyDatabase.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/LockedActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/settings/SettingsFragment.kt
app/src/main/java/com/philkes/notallyx/presentation/viewmodel/BaseNoteModel.kt
app/src/main/java/com/philkes/notallyx/presentation/viewmodel/preference/NotallyXPreferences.kt
app/src/main/java/com/philkes/notallyx/utils/backup/ExportExtensions.kt
app/src/main/java/com/philkes/notallyx/utils/security/EncryptionUtils.kt
app/src/main/java/com/philkes/notallyx/utils/security/SQLCipherUtils.java

Fix database file path when data in public folder enabled

---

app/src/main/java/com/philkes/notallyx/NotallyXApplication.kt
app/src/main/java/com/philkes/notallyx/data/dao/BaseNoteDao.kt
app/src/main/java/com/philkes/notallyx/presentation/UiExtensions.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/ConfigureWidgetActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/widget/WidgetFactory.kt
app/src/main/java/com/philkes/notallyx/presentation/widget/WidgetProvider.kt
app/src/main/java/com/philkes/notallyx/utils/AndroidExtensions.kt
app/src/main/res/layout-v31/widget_list_child_item.xml
app/src/main/res/layout-v31/widget_list_item.xml
app/src/main/res/layout/widget.xml
app/src/main/res/layout/widget_list_child_item.xml
app/src/main/res/layout/widget_list_header.xml
app/src/main/res/layout/widget_list_item.xml
app/src/main/res/layout/widget_note.xml
app/src/main/res/values/colors.xml

Closes #300 
- Widgets have same color as notes
- This also respects dark/light theme
[notallyx_issues_300.webm](https://github.com/user-attachments/assets/26b6a917-7e7e-419f-b0c8-b661fd1ec00e)

Color widgets in note's color

---

app/src/main/java/com/philkes/notallyx/presentation/activity/LockedActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/action/ActionBottomSheet.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/action/AddBottomSheet.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/action/AddNoteBottomSheet.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/action/MoreListBottomSheet.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/action/MoreNoteBottomSheet.kt
app/src/main/java/com/philkes/notallyx/presentation/viewmodel/BaseNoteModel.kt
app/src/main/java/com/philkes/notallyx/presentation/viewmodel/NotallyModel.kt
app/src/main/java/com/philkes/notallyx/utils/backup/ExportExtensions.kt

Closes #315 and Closes #316
[notallyx_issues_315.webm](https://github.com/user-attachments/assets/2e635ce0-88bf-4739-8f53-43e55ddb41e2)

Add Export option to Note more options

---

app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListManager.kt
app/src/main/java/com/philkes/notallyx/utils/changehistory/ChangeCheckedForAllChange.kt
app/src/main/java/com/philkes/notallyx/utils/changehistory/DeleteCheckedChange.kt
app/src/test/kotlin/com/philkes/notallyx/recyclerview/listmanager/ListManagerAddDeleteTest.kt
app/src/test/kotlin/com/philkes/notallyx/recyclerview/listmanager/ListManagerCheckedTest.kt
app/src/test/kotlin/com/philkes/notallyx/test/TestUtils.kt

Simplify DeleteCheckedChange and ChangeCheckedForAllChange

---

app/src/main/java/com/philkes/notallyx/presentation/UiExtensions.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
app/src/main/java/com/philkes/notallyx/utils/ColorActivityExtensions.kt

Closes #339 and fixes described problem in https://github.com/PhilKes/NotallyX/issues/187#issuecomment-2627778043

Navigate to startView on back press and make ColorEditDialog full size

---

app/src/main/java/com/philkes/notallyx/data/model/ListItemExtensions.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListManager.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/sorting/ListItemSortedListExtensions.kt

Fixes #330 
- Item orders of checked items were incorrectly updated

Fix item orders when dragging unchecked into checked

---

app/src/main/java/com/philkes/notallyx/presentation/UiExtensions.kt
app/src/main/java/com/philkes/notallyx/utils/ColorActivityExtensions.kt
app/src/main/res/layout/dialog_color.xml

Fix wrong title/message in delete color dialog

---

app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/sorting/ListItemSortedListExtensions.kt
app/src/test/kotlin/com/philkes/notallyx/recyclerview/listmanager/ListManagerMoveTest.kt

Fixes #330 
[notallyx_issues_345.webm](https://github.com/user-attachments/assets/f2e00e4b-31ff-4bd5-929e-6117bc5c62cf)

Fix ListItem order updates when dragging

---

app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListItemVH.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListManager.kt
app/src/test/kotlin/com/philkes/notallyx/recyclerview/listmanager/ListManagerCheckedTest.kt

Fix add new item after current on next pressed

---

app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListItemDragCallback.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListManager.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/sorting/ListItemSortedListExtensions.kt
app/src/test/kotlin/com/philkes/notallyx/recyclerview/listmanager/ListManagerAddDeleteTest.kt
app/src/test/kotlin/com/philkes/notallyx/recyclerview/listmanager/ListManagerCheckedTest.kt
app/src/test/kotlin/com/philkes/notallyx/recyclerview/listmanager/ListManagerMoveTest.kt
app/src/test/kotlin/com/philkes/notallyx/recyclerview/listmanager/ListManagerTestBase.kt

Fix ListItem drag reset isDragged flag

---

app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListItemDragCallback.kt
app/src/test/kotlin/com/philkes/notallyx/recyclerview/listmanager/ListManagerMoveTest.kt
app/src/test/kotlin/com/philkes/notallyx/test/TestUtils.kt

Fix child item startDrag call

---

app/src/main/java/com/philkes/notallyx/presentation/viewmodel/preference/NotallyXPreferences.kt

Refresh backupOnSave on settings import

---

app/src/main/java/com/philkes/notallyx/presentation/UiExtensions.kt

Fix TextView selectionHandleColor for API smaller 28

---

app/src/main/java/com/philkes/notallyx/utils/backup/AutoBackupWorker.kt
app/src/main/java/com/philkes/notallyx/utils/backup/ExportExtensions.kt

Try send notification if backup folder does not exist

---

app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListItemCollectionExtensions.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListItemDragCallback.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListManager.kt
app/src/test/kotlin/com/philkes/notallyx/recyclerview/listmanager/ListManagerMoveTest.kt

Only make moved items child if item below is child

---

app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/viewmodel/NotallyModel.kt

Correctly reload state if EditActivity was destroyed by system

---

app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListManager.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/adapter/ListItemVH.kt
app/src/test/kotlin/com/philkes/notallyx/recyclerview/listmanager/ListManagerMoveTest.kt

Fix always check previous parent for checked on finishMove

---

app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
app/src/main/java/com/philkes/notallyx/utils/ActionMode.kt

Lock delete action while already deleting note

---

app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListItemDragCallback.kt
app/src/test/kotlin/com/philkes/notallyx/recyclerview/listmanager/ListManagerMoveTest.kt
app/src/test/kotlin/com/philkes/notallyx/recyclerview/listmanager/ListManagerTestBase.kt

Call finishMove if ListItem dragged to same position

---

app/src/main/java/androidx/recyclerview/widget/NestedScrollViewItemTouchHelper.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditListActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListItemDragCallback.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListManager.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/adapter/CheckedListItemAdapter.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/adapter/ListItemAdapter.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/adapter/ListItemAdapterBase.kt
app/src/test/kotlin/com/philkes/notallyx/recyclerview/listmanager/ListManagerTestBase.kt

Fixes #396 
- Add's auto-scroll when dragging an item to the top/bottom of the scroll view:
[notallyx_issues_396.webm](https://github.com/user-attachments/assets/4aceb545-e8d3-4f9d-91ee-4a45db63e157)
- When using undo/redo the list also scroll back to the changed item

Add auto-scroll when dragging ListItem to top/bottom

---

app/src/main/java/com/philkes/notallyx/utils/backup/ExportExtensions.kt

Fix databaseFile path when creating backup

---

app/src/main/java/com/philkes/notallyx/presentation/UiExtensions.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListManager.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/adapter/ListItemVH.kt
app/src/main/java/com/philkes/notallyx/utils/changehistory/ChangeHistory.kt
app/src/main/java/com/philkes/notallyx/utils/changehistory/ListEditTextChange.kt
app/src/test/kotlin/com/philkes/notallyx/changehistory/ChangeHistoryTest.kt

Closes #244 
- Adds long-click to undo/redo buttons to undo/redo all changes
- Adds ripple effect to bottom appbar action buttons when pressing them

Long click to undo/redo all

---

app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/adapter/ListItemVH.kt

Strike-through checked ListItems

---

app/src/main/java/com/philkes/notallyx/utils/security/SQLCipherUtils.java

Make sure decrypted DB cache file is deleted before decrypting

---

app/src/main/java/com/philkes/notallyx/presentation/UiExtensions.kt

Fix ignoring system SuggestionSpan changes

---

app/src/main/java/com/philkes/notallyx/data/dao/BaseNoteDao.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/note/PickNoteActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/viewmodel/BaseNoteModel.kt

Closes #398 
- Archived notes are now shown in the label specific view

Display archived notes in label view

---

app/src/main/java/com/philkes/notallyx/data/imports/txt/PlainTextImporter.kt
app/src/main/java/com/philkes/notallyx/utils/AndroidExtensions.kt
app/src/main/java/com/philkes/notallyx/utils/backup/ExportExtensions.kt

Fix file append mode not working with WebDAV backup Folder

---

app/src/main/java/com/philkes/notallyx/presentation/view/misc/EditTextWithWatcher.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/adapter/ListItemVH.kt

Fix next action on ListItem EditText

---

app/schemas/com.philkes.notallyx.data.NotallyDatabase/9.json
app/src/main/java/com/philkes/notallyx/data/NotallyDatabase.kt
app/src/main/java/com/philkes/notallyx/data/imports/evernote/EvernoteImporter.kt
app/src/main/java/com/philkes/notallyx/data/imports/google/GoogleKeepImporter.kt
app/src/main/java/com/philkes/notallyx/data/imports/txt/PlainTextImporter.kt
app/src/main/java/com/philkes/notallyx/data/model/BaseNote.kt
app/src/main/java/com/philkes/notallyx/data/model/Converters.kt
app/src/main/java/com/philkes/notallyx/data/model/ListItem.kt
app/src/main/java/com/philkes/notallyx/data/model/ModelExtensions.kt
app/src/main/java/com/philkes/notallyx/data/model/NoteViewMode.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/settings/SettingsFragment.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditListActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditNoteActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/adapter/CheckedListItemAdapter.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/adapter/ListItemAdapter.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/adapter/ListItemAdapterBase.kt
app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/adapter/ListItemVH.kt
app/src/main/java/com/philkes/notallyx/presentation/viewmodel/NotallyModel.kt
app/src/main/java/com/philkes/notallyx/presentation/viewmodel/preference/NotallyXPreferences.kt
app/src/main/java/com/philkes/notallyx/presentation/viewmodel/preference/Preference.kt
app/src/main/java/com/philkes/notallyx/utils/backup/ImportExtensions.kt
app/src/main/java/com/philkes/notallyx/utils/backup/XmlParserExtensions.kt
app/src/main/res/layout/fragment_settings.xml
app/src/test/kotlin/com/philkes/notallyx/data/imports/google/GoogleKeepImporterTest.kt
app/src/test/kotlin/com/philkes/notallyx/data/model/ModelExtensionsTest.kt

Closes #497 
- Persists `viewMode` for each note individually
- Removed obsolete `Default Note View Mode` preference

Persist viewMode for each note individually

---

app/build.gradle.kts
app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/NotallyFragment.kt

Fix search navigate up loop and navigate label crash

---

app/src/main/res/layout/dialog_input.xml

Remove capitalization in input dialogs

---

app/src/main/java/com/philkes/notallyx/utils/AndroidExtensions.kt

Fix share pure text note

---

app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditNoteActivity.kt

Fix setting movementmethod for links

---

app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
app/src/main/res/values-v27/themes.xml
app/src/main/res/values/themes.xml

Fixes https://github.com/PhilKes/NotallyX/issues/515#issuecomment-2787597973

Fix navigationBarColor in Note and BottomSheetFragments for API < 27

---

app/src/main/res/layout/dialog_reminder_repetition.xml

Reduce reminder dialog padding and add scrolling

---

app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListItemCollectionExtensions.kt

Fix ListItem deletion order and repair broken parent check state

---

app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/SearchFragment.kt
app/src/main/java/com/philkes/notallyx/utils/ActionMode.kt

Update selected notes when search query is changed

---

app/src/main/java/com/philkes/notallyx/utils/AndroidExtensions.kt

Fix checking for existing backup logs file

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt

Add intent-filter to open any text based file

---

app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/adapter/ListItemVH.kt

Make checked ListItem non editable

---

app/src/main/java/com/philkes/notallyx/NotallyXApplication.kt
app/src/main/java/com/philkes/notallyx/presentation/widget/WidgetProvider.kt

Fix showing widget when actually locked

---

app/src/main/java/com/philkes/notallyx/utils/backup/ExportExtensions.kt

Fix export PDF file name if title is blank

---

app/src/main/java/com/philkes/notallyx/utils/AlarmExtensions.kt

Use note.id and reminder.id for reminder requestCode

---

app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt

Fix convertTo action using updated model
