PhilKes/NotallyX

- app/src/main/java/com/omgodse/notally/activities/NotallyActivity.kt
Fixes #11 
If the user tries to open an attached file for which there is no suitable app installed, he will be shown an empty `IntentChooser`:
[notally_open_file_no_app.webm](https://github.com/user-attachments/assets/fdd98c2e-0897-46f6-9d08-30d838daa54b)
> Show appchooser when opening file for which there is no suitable app installed

- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditNoteActivity.kt
- app/src/main/java/com/philkes/notallyx/utils/Extensions.kt
- app/src/main/java/com/philkes/notallyx/utils/changehistory/EditTextChange.kt
- app/src/main/java/com/philkes/notallyx/utils/changehistory/ValueChange.kt
- app/src/main/res/layout/activity_edit.xml
Closes #47 
* Adds all formatting changes to `ChangeHistory`
* Reworks the `Clear Formatting` action, so that it does not simply delete the whole formatted `Span` but instead only removes the selected text from the `Span`
* If you click outside of the `EditText` in `EditNoteActivity` the `EditText` is automatically focused
> Add text formatting to ChangeHistory and fix Clear Formatting action

- app/src/main/java/com/philkes/notallyx/presentation/activity/ConfigureWidgetActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/LabelsFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/NotallyFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditListActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/main/BaseNoteAdapter.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/main/BaseNoteVH.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/main/ColorAdapter.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/main/ColorVH.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/main/LabelAdapter.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/main/LabelVH.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListItemAdapter.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListItemDragCallback.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListItemListener.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListItemVH.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListManager.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/MakeListVH.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/preview/PreviewFileAdapter.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/preview/PreviewFileVH.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/preview/PreviewImageAdapter.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/preview/PreviewImageVH.kt
- app/src/test/kotlin/com/philkes/notallyx/recyclerview/listmanager/ListManagerMoveTest.kt
- app/src/test/kotlin/com/philkes/notallyx/recyclerview/listmanager/ListManagerTestBase.kt
- app/src/test/kotlin/com/philkes/notallyx/test/TestUtils.kt
Might fix #12 
So I think the problem that it sometimes seems like the CheckBox toggling is not working is not related to any backup, move or subtask issue, but rather that when you toggle the CheckBox it triggers an `RecyclerView.Adapater.notifyItemChanged` which in turn sets the value of the CheckBox again. Now if the user toggles the CheckBox, and while the `OnCheckedChangeListener` is still executed the user toggles it again, this change will be immediately overwritten by the  `RecyclerView.Adapater.notifyItemChanged` of the previous toggle. There is always a slight delay between the user toggling the CheckBox and the `OnCheckedChangeListener` completing, not much you can do about that.
With this PR i disabled the `OnCheckedChangeListener` while it is running, meaning if the user …
> Fix ListItem.checked updates if toggled very fast

- app/src/main/java/com/philkes/notallyx/data/model/Converters.kt
- app/src/main/java/com/philkes/notallyx/data/model/SpanRepresentation.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditNoteActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/viewmodel/NotallyModel.kt
- app/src/main/java/com/philkes/notallyx/utils/Extensions.kt
- app/src/main/java/com/philkes/notallyx/utils/backup/XMLUtils.kt
- app/src/main/res/layout/update_link_dialog.xml
- app/src/main/res/values/strings.xml
Closes #40 
* When pasting a URL it will automatically be inserted as a clickable `URLSpan`
*  Added `Copy` action when you click on a link
* When a text is selected and you choose `Link` in the ActionContextMenu the Text is transformed into a `URLSpan` with a link to the URL in your Clipboard
* You can edit the URL of a Link with the `Edit` action when you click a Link
[notally_issues_40.webm](https://github.com/user-attachments/assets/1c4b10fb-9e03-4502-830d-f4ddd14f284e)
> Rework pasting Link and editing

- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditListActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditNoteActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/widget/WidgetFactory.kt
Fixes #61 
* Changes to the title `EditText` are now added to the `ChangeHistory`, thereby the modified timestamp is also updated when only the title was modified  
[notallyx_issues_61.webm](https://github.com/user-attachments/assets/7e0053da-2b32-46f3-90b6-f2007aea51fb)
> Add EditActivity title EditText to ChangeHistory

- app/src/main/java/com/philkes/notallyx/presentation/activity/LockedActivity.kt
- app/src/main/java/com/philkes/notallyx/utils/security/LockUtils.kt
Fixes #58 
* Call `LockedActivity.finish()` for **any** authentication error during Biometric/PIN unlock
[notallyx_issues_58.webm](https://github.com/user-attachments/assets/328985c1-d24c-4db0-8159-da61f4e8c0c0)
(1st time Android back button was pressed when unlock is shown)
> Finish LockedActivity for any authentication error

- app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListItemDragCallback.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListItemVH.kt
- app/src/main/res/layout/activity_edit.xml
Fixes #67 
* Allows to swipe a `ListItemVH` on the `DragHandle`:
[notallyx_issues_67.webm](https://github.com/user-attachments/assets/d086a1c2-edc4-4b2a-bc74-af844f98613d)
Note: If you already started a swipe to left/right you cant start a up/down drag in the same Drag motion, since this would mean fusing the `SwipeLayout` and `ListItemDragCallback` together, which takes much more effort
> Allow to swipe on ListItemVH DragHandle

- app/src/main/java/com/philkes/notallyx/presentation/UiExtensions.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/LockedActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/NotallyFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/SearchFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/SettingsFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditNoteActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/PlayAudioActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/RecordAudioActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/ViewImageActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/main/ColorAdapter.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/misc/EditTextWithHistory.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListItemDragCallback.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListManager.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/sorting/ListItemSortedList.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/sorting/ListItemSortedListExtensions.kt
- app/src/main/java/com/philkes/notallyx/presentation/widget/WidgetProvider.kt
- app/src/main/java/com/philkes/notallyx/utils/audio/AudioRecordService.kt
- app/src/main/java/com/philkes/notallyx/utils/security/LockUtils.kt
See #82 
* Replaces deprecated `startActivityForResult` with [ActivityResultLauncher](https://developer.android.com/reference/androidx/activity/result/ActivityResultLauncher)
* Adds some minor version checks for deprecated usages
> Migrate startActivityForResult and other minor deprecations

- app/src/main/java/com/philkes/notallyx/data/NotallyDatabase.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/widget/WidgetProvider.kt
- app/src/main/java/com/philkes/notallyx/utils/Operations.kt
- app/src/main/java/com/philkes/notallyx/utils/backup/AutoBackupWorker.kt
- app/src/main/java/com/philkes/notallyx/utils/backup/Export.kt
- app/src/main/java/com/philkes/notallyx/utils/backup/Import.kt
Fixes #101 
* `exportZip` no longer uncessarily tries to call `preferences.biometricLock.observeForever` which crashes since its run on a background thread
* Limits the extra log file for exceptions to be overwritten when it gets larger than 2kB
> Dont observe BiometricLock in zip auto-backup

- app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/ArchivedFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/DeletedFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/NotallyFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/NotesFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/SearchFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/PickNoteActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/main/BaseNoteAdapter.kt
- app/src/main/java/com/philkes/notallyx/presentation/viewmodel/BaseNoteModel.kt
Fixes #117 
* Pass correct note ids to delete forever
* Show useful actions in the Folders: `NOTES`: `Pin`, `Label`, `Delete`, `ARCHIVED`: `Unarchive`, `Delete`, `Export`, `DELETED`: `Restore`, `Delete Forever`. All other actions are hidden in the "..." menu
> Fix delete selected notes forever

- app/src/main/java/com/philkes/notallyx/presentation/UiExtensions.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/misc/EditTextWithHistory.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListManager.kt
- app/src/main/java/com/philkes/notallyx/presentation/viewmodel/NotallyModel.kt
- app/src/main/java/com/philkes/notallyx/utils/changehistory/EditTextWithHistoryChange.kt
- app/src/main/java/com/philkes/notallyx/utils/changehistory/ListEditTextChange.kt
- app/src/main/java/com/philkes/notallyx/utils/changehistory/ListPositionValueChange.kt
- app/src/main/java/com/philkes/notallyx/utils/changehistory/ValueChange.kt
Closes #124 and closes #125 
* Before, the note was only saved if there are any changes pushed to `ChangeHistory`, now it's saved if any fields of `BaseNote` differ to when the note was initially opened
* Fixed crashes when setting the cursor position on undo/redo action
[notallyx_issues_124.webm](https://github.com/user-attachments/assets/e5a4e430-a799-43b9-af8f-105ac921e705)
> Save note if any BaseNote fields changed + fix cursor position on undo/redo

- app/src/main/java/com/philkes/notallyx/NotallyXApplication.kt
- app/src/main/java/com/philkes/notallyx/data/NotallyDatabase.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/SettingsFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/viewmodel/BaseNoteModel.kt
- app/src/main/java/com/philkes/notallyx/presentation/viewmodel/preference/AutoBackup.kt
- app/src/main/java/com/philkes/notallyx/presentation/viewmodel/preference/NotallyXPreferences.kt
- app/src/main/java/com/philkes/notallyx/presentation/viewmodel/preference/Preference.kt
- app/src/main/java/com/philkes/notallyx/presentation/widget/WidgetProvider.kt
- app/src/main/java/com/philkes/notallyx/utils/IO.kt
- app/src/main/java/com/philkes/notallyx/utils/backup/AutoBackupWorker.kt
- app/src/main/java/com/philkes/notallyx/utils/backup/Export.kt
- app/src/main/java/com/philkes/notallyx/utils/backup/Import.kt
- app/src/main/java/com/philkes/notallyx/utils/security/EncryptionUtils.kt
- app/src/main/res/layout/fragment_settings.xml
- app/src/main/res/layout/preference_boolean_dialog.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/provider_paths.xml
Closes #109 
* Adds preference to move all internal data to external storage. This can be used to synchronize the data across multiple devices, or even make backups with other external apps or webdav shares.
> Add setting to store all data on external storage

- app/src/main/java/android/print/PostPDFGenerator.kt
- app/src/main/java/com/philkes/notallyx/data/imports/ExternalImporter.kt
- app/src/main/java/com/philkes/notallyx/data/imports/NotesImporter.kt
- app/src/main/java/com/philkes/notallyx/data/imports/txt/PlainTextImporter.kt
- app/src/main/java/com/philkes/notallyx/data/model/ModelExtensions.kt
- app/src/main/java/com/philkes/notallyx/presentation/UiExtensions.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/SettingsFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/PlayAudioActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/ViewImageActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/viewmodel/BaseNoteModel.kt
- app/src/main/java/com/philkes/notallyx/utils/backup/Export.kt
- app/src/main/res/values/strings.xml
Closes #103 and closes #62
* Adds import from `Plain Text Files` to `Import Notes from other App`
- 1 File = 1 Note (Note title is equal to file's name without the extension)
- Files can have any extension but must contain plain text
- If the text files start with either Markdown list syntax (e.g. " - [x] XYZ" or Notally's current txt syntax (e.g. "[✓] XYZ") the file is imported as a Task List Note
- There is no text formatting being imported, if you e.g. import a markdown file its contents are interpreted as plain text (except for the list syntax, as described above)
- The importer also searches all subfolders recursively for files
* If you select multiple notes its now possible to export them to PDF, JSON, TXT or HTML at once (1 Note = 1 File) …
> Add plain text importer + export multiple notes

- app/src/main/java/com/philkes/notallyx/presentation/UiExtensions.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
- app/src/main/java/com/philkes/notallyx/utils/backup/Export.kt
Fixes #143 and fixes #144
* Correctly sets file name to note's title for single note export:
[notallyx_issues_143.webm](https://github.com/user-attachments/assets/e2f9a3ce-e430-4f47-9640-306055d31a88)
* If multiple notes with the same title are exported they are not overwritten but instead their file name have " (XYZ)" appended: 
[notallyx_issues_142_duplicate_export_names.webm](https://github.com/user-attachments/assets/d958b2b0-a2ce-4f98-a784-da586f8efc37)
> Note export file name fixes

- app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListItemVH.kt
Fixes #142 
Ensures that the list item is only removed if the text is empty and backspace/delete key is pressed.
Tested with chinese input keyboard:
[notallyx_issues_142_chinese_del.webm](https://github.com/user-attachments/assets/9cba947b-ac8d-48da-bbea-05d2fbac23be)
> Fix delete list item on DEL key pressed

- app/src/main/java/com/philkes/notallyx/data/imports/txt/PlainTextExtensions.kt
- app/src/main/java/com/philkes/notallyx/data/imports/txt/PlainTextImporter.kt
- app/src/main/java/com/philkes/notallyx/presentation/UiExtensions.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/misc/EditTextAutoClearFocus.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/misc/EditTextWithHistory.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/misc/EditTextWithWatcher.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListItemVH.kt
- app/src/main/res/values/strings.xml
- app/src/test/kotlin/com/philkes/notallyx/data/imports/txt/PlainTextExtensionsTest.kt
Closes #150 
When pasting list-like text into a list note its automatically parsed into separate list items.
You can see all supported list syntaxes here:
[notallyx_issues_150_paste_list.webm](https://github.com/user-attachments/assets/88fa1af2-4d4b-4af2-a66e-3ffebbe69016)
For Markdown and NotallyX syntax it also parses the checkbox value.
If any items in the original text are indented they are parsed and indented as child list items
All the described syntaxes are also supported when importing text files.
> Parse list syntax on paste in list note

- app/src/main/java/com/philkes/notallyx/presentation/UiExtensions.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditNoteActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/misc/StylableEditTextWithHistory.kt
- app/src/main/res/values-de/strings.xml
Closes #166 
* If the user tries to link a note that has no title, a dialog to enter a custom display-text for the link is shown:
[notallyx_issues_166.webm](https://github.com/user-attachments/assets/b92abeca-5476-4f7e-a068-3f06e6f23b49)
* You can also change the display-text of the note-link afterwards: 
[notallyx_issues_166_2.webm](https://github.com/user-attachments/assets/bb6dc89b-0375-4f07-ae4a-e1627d4ab929)
> Show edit link dialog when note without title is linked

- app/src/main/java/com/philkes/notallyx/data/model/ModelExtensions.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/misc/StylableEditTextWithHistory.kt
Closes #157 
When pasting a text containing more than just a url, links are now correctly converted to clickable spans:
[notallyx_issues_157.webm](https://github.com/user-attachments/assets/35be97eb-1429-4f1a-89ba-87d27da35c96)
> Add clickable spans when text containing urls is pasted

- app/src/main/java/com/philkes/notallyx/utils/security/LockUtils.kt
Please let me know if there are any issues or areas for improvement. :)
> Fix biometric lock issue on devices running Android 10 or 9

- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/SettingsFragment.kt
Fixes #192 
Before: While the user is dragging a slider in the settings the onChange events were constantly triggered
After: The onChange event is only triggered once the user stops dragging the slider
> Fix settings Slider debounce

- app/src/main/java/com/philkes/notallyx/presentation/UiExtensions.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/NotallyFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/settings/PreferenceBindingExtensions.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/settings/SettingsFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/PickNoteActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/main/BaseNoteAdapter.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/main/BaseNoteVH.kt
- app/src/main/java/com/philkes/notallyx/presentation/viewmodel/preference/NotallyXPreferences.kt
- app/src/main/res/layout/activity_edit.xml
- app/src/main/res/layout/fragment_settings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/strings.xml
See #176 
- Added setting to hide labels in notes overview
- Fixes the bottom appbar cutting off the notes content
- Slightly decreased the bottom appbar height + increased size of menu buttons:
> Fix bottom appbar cutoff + add setting to hide labels in notes overview

- app/src/main/java/com/philkes/notallyx/presentation/view/main/BaseNoteVH.kt
Fixes #215 
Resets `BaseNoteVH.binding.Title` left drawable if note is not a list
> Fix display of list icon in BaseNoteVH

- app/src/main/res/layout/text_input_dialog_2.xml
Fixes #181 
Makes the Edit Link Dialog scrollable if there is not enough space vertically:
> Make DialogTextInput2 scrollable vertically

- app/src/main/res/layout/recycler_base_note.xml
Closes #220 
Added `ellipsize=end` to Title and Note text in `BaseNoteVH` to show the user if there are more characters in a Note's title and content
With max title lines = 1 and max content lines = 1:
> Add end-ellipsize for Title and Note in BaseNoteVH

- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditListActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/action/MoreNoteBottomSheet.kt
Closes #206 
- Moves all actions from the top "..." menu to the bottom "..."
- On the top the remaining actions are: Search, Pin, Delete (or Restore if note is in Deleted, or Unarchive if note is in Archived)
<p> 
</p>
> Move top more menu actions to bottom in EditActivity

- app/src/main/java/com/philkes/notallyx/data/imports/NotesImporter.kt
- app/src/main/java/com/philkes/notallyx/data/imports/txt/PlainTextImporter.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/settings/SettingsFragment.kt
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values/strings.xml
Fixes #209 
- Allows to either pick a single text file or an entire folder
- Restricts text files import to the following file mimetypes (other file types are ignored):
- `text/*`
- `application/json`
- `application/xml`
- `application/javascript`
- `application/xhtml+xml`
- `application/yaml`
[notallyx_issues_209.webm](https://github.com/user-attachments/assets/c282a7f3-335c-4e72-931d-9b17b6cca14c)
> Import either single text file or entire folder + restrict plain text import mimetypes

- app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/settings/SettingsFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditNoteActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/PlayAudioActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/ViewImageActivity.kt
- app/src/main/java/com/philkes/notallyx/utils/Extensions.kt
- app/src/main/java/com/philkes/notallyx/utils/Operations.kt
Fixes #227
Wraps all `Intent`s that use an external app (like picking a file/folder, opening link/file,...) in a `IntentChooser`. If the user has multiple possible receiver apps for the given Intent it will let the user select one, e.g. when trying to open a PDF file:
[notallyx_issues_227.webm](https://github.com/user-attachments/assets/a6905b5c-2189-4e87-a083-9a2ea80e422b)
If the user has no compatible app installed he will see:
> Add IntentChooser to all external app Intents

- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
- app/src/main/java/com/philkes/notallyx/utils/Extensions.kt
- app/src/main/java/com/philkes/notallyx/utils/Operations.kt
Fixes #243 
There seems to be size limit for the payload of a `ACTION_SEND` intent, at 1MB, but this does not directly correspond to the sent text size. 
This PR limits the amount of characters being send via the share action to 150000, which is a lot and well under the limitation.
I did not encounter any problems with notes below this. If a note is bigger than 150000 the send text is truncated to that maximum length (with "...more characters") at the end, but I doubt anyone will create notes that big instead of just splitting them.
> Limit sharing to 150000 characters due not exceed builtin limit

- app/src/main/java/com/philkes/notallyx/presentation/UiExtensions.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditListActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditNoteActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/main/BaseNoteVH.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/main/ColorVH.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/TextFormattingAdapter.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/ToggleAdapter.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/ToggleVH.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/action/ActionBottomSheet.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/action/AddBottomSheet.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/action/AddNoteBottomSheet.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/action/MoreListBottomSheet.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/action/MoreNoteBottomSheet.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/audio/AudioAdapter.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/audio/AudioVH.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/preview/PreviewFileAdapter.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/preview/PreviewFileVH.kt
- app/src/main/java/com/philkes/notallyx/utils/Operations.kt
- app/src/main/res/color/toggle_background.xml
- app/src/main/res/layout/activity_edit.xml
- app/src/main/res/layout/bottom_sheet_action.xml
- app/src/main/res/layout/label.xml
- app/src/main/res/layout/recycler_base_note.xml
- app/src/main/res/layout/recycler_toggle.xml
- app/src/main/res/values/colors.xml
Closes #264 
Re-colors Toolbars, BottomAppBar, BottomSheets, EditText cursor + selection drawables, navigation + status bar, Searchbar according to note's color
[notallyx_issues_264.webm](https://github.com/user-attachments/assets/0be42f8c-f113-4902-827a-e7de4ee24bee)
> Display entire interface in note's color

- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/viewmodel/NotallyModel.kt
Fixes #288 
When you exit from an empty note, it is deleted. Skip checking for auto-save when that happens
> Fix do not checkAutoSave if empty note was deleted

- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/NotallyFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditListActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditNoteActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/misc/EditTextWithWatcher.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/note/listitem/ListItemVH.kt
Fixes #293 
- On orientation change the cursor and scroll posoitions are restored
- This also includes scroll position in any notes overview Views
> Re-set cursor and scroll position on orientation change

- app/src/main/java/com/philkes/notallyx/presentation/UiExtensions.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/DeletedFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/LabelsFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/settings/PreferenceBindingExtensions.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/settings/SettingsFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditNoteActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/PlayAudioActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/SelectLabelsActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/ViewImageActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/reminders/RemindersActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/view/misc/StylableEditTextWithHistory.kt
Fixes #302  and Fixes #201 
- Decreases the background insets for all input dialogs for all sides to 0
- Allows input dialogs to use entire width
<p>
<p/>
<p>
</p>
For Links the Remove/Clear behaviour is as follows:
1. If the link's text and URL are the same:
- Click Link -> "Remove Link" -> will remove the Hyperlink *and* the displayed text, since they are equal
2. If the link's text and URL are different:
- Click Link -> "Remove Link" -> will remove the Hyperlink *but not* the displayed text
2. If the link is a note link:
- Click Link -> "Remove Link" -> will remove the Hyperlink *and* the displayed text
For any of these scenarios the hyperlink can be removed without removing the displayed text via:
Click Link -> "Edit" (Or click hyperlink symbol in bottom bar if link text is selected) …
> Increase input dialog sizes to fit large keyboards

- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditListActivity.kt
- app/src/main/java/com/philkes/notallyx/utils/AndroidExtensions.kt
- app/src/main/java/com/philkes/notallyx/utils/ErrorActivity.kt
- app/src/main/res/layout/activity_error.xml
Improves crash behaviour for #402 
- When the app crashes when editing/viewing a note, the note is saved before the `ErrorActivity` is shown
- Added first line of Exception stacktrace to `ErrorActivity` view
> Save open note on crash

- app/src/main/java/com/philkes/notallyx/presentation/view/note/action/ActionBottomSheet.kt
- app/src/main/res/layout/dialog_color_picker.xml
Fixes #444
- Maximize ActionBottomSheets and allow scrolling
Before vs After:
<p>
</p>
- Add scrolling to DialogColorPicker
> Maximize ActionBottomSheets and allow scrolling

- app/src/main/java/com/philkes/notallyx/presentation/UiExtensions.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/LabelsFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
Closes #180 
- When clicking a label inside a note you can view all notes with that label
- When long clicking a label inside a note you can edit that label
[notallyx_issues_180.webm](https://github.com/user-attachments/assets/711ddd80-85bb-404c-aa24-04770a31c348)
> Hide hidden labels in overview and quick jump to label from note view

- app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/LabelsFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/NotallyFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/fragment/settings/SettingsFragment.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/PickNoteActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/viewmodel/BaseNoteModel.kt
- app/src/main/java/com/philkes/notallyx/presentation/viewmodel/preference/NotallyXPreferences.kt
- app/src/main/res/layout-v26/recycler_label.xml
- app/src/main/res/layout/recycler_label.xml
Closes #401 
- When a label is hidden in the "Labels" View, the notes with that label are also hidden in the notes overview
> Do not show hidden labels in notes overview

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/philkes/notallyx/data/model/ModelExtensions.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/main/MainActivity.kt
- app/src/main/java/com/philkes/notallyx/presentation/activity/note/EditActivity.kt
- app/src/main/java/com/philkes/notallyx/utils/AndroidExtensions.kt
Closes #380 
Closes #281 
- Add attached images to share note: 
[notallyx_issues_380.webm](https://github.com/user-attachments/assets/adfaa890-b5e6-4d61-8c97-692206e465a0)
- Support sharing images/files to the app: 
[notallyx_issues_281.webm](https://github.com/user-attachments/assets/3a704f97-a250-4f26-ab23-6819898960c2)
> Add attached images to share note and support sharing files to the app
